# $X=/home/ubuntu
services:
  couchbase:
    container_name: couchbase
    command:
      - tail
      - -f
      - /dev/null
    image: couchbase/server:enterprise-6.6.2
    volumes:
      - $X/vscode/docker/couchbase-upgrade:/app:ro
    network_mode: host
  init-couchbase:
    # Refer https://stackoverflow.com/questions/70322031/does-docker-compose-support-init-container
    container_name: init-couchbase
    command:
      - /bin/bash
      - -c
      - docker exec couchbase /bin/bash -c /app/init-standalone-6.6.2.sh
    depends_on:
      - couchbase
    image: init-container:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



